# Generated by Django 5.2.16 on 2026-07-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
